// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phonxpohadomblynnzld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBob254cG9oYWRvbWJseW5uemxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjcxMTMsImV4cCI6MjA1MTg0MzExM30.-j1y8CSqgfJ5HzuXLYTTIPkQ24oKMLjmIbgXNZPGmM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
